name: "Bug Report"
description: "Use this user-friendly form to report bugs to us"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this report form to help us help you easier. Thanks!
  # First let's ask the user about the bug
  - type: input
    id: bug-link
    attributes:
      label: Link of bug-page
      description: |
        Copy-paste the link from your browser.
      placeholder:
    validations:
      required: false
  - type: input
    id: screenshot
    attributes:
      label: Screenshot
      description: |
        Could you add a screenshot?.
      placeholder: Paste the Screenshot
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please be holistic in your description: Even seemingly trivial things
        may contain the important clue to fix the bug. If applicable, also tell
        us what you expect to happen instead.
      placeholder: Describe your bug and the expected behaviour here.
    validations:
      required: true
  # Also ask them to describe reproducing the bug
  - type: textarea
    id: reproducing
    attributes:
      label: Reproducing
      description: |
        What steps do you need to take in order to make the bug happen? We need
        this information to be able to find the bug. We can only fix what we can
        see on our side. The more contextual information you include the better.
      placeholder: How can we make this issue occur?
    validations:
      required: true
  # Also, we need to know the operating system(s) where this happens
  - type: checkboxes
    id: scope
    attributes:
      label: Your Platform
      description: |
        Please tell us what platform you're on. If you were able to check other
        operating systems and they have the same bug, please check all operating
        systems that apply!
      options:
        - label: Windows
        - label: macOS
        - label: Linux
        - label: Android
        - label: iOS
  - type: input
    id: Browser
    attributes:
      label: Browser
      description: |
        Which [Browser](https://www.whatsmybrowser.org/) are you using?
      placeholder: Which Browser are you using?
    validations:
      required: false
  - type: input
    id: Device
    attributes:
      label: Device
      description: |
        Information about the device, version etc.
      placeholder: Which device are you using?
    validations:
      required: false
  - type: textarea
    id: more-info
    attributes:
      label: Additional Information
      description: |
        If applicable, feel free to include more info, such as log outputs or
        error messages you are seeing.
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report. We'll get
        back to you as soon as possible. Please check your notifications
        regularly and respond quickly to any additional questions we have. This
        ensures that we can timely address the issue.
